// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvXbKCUaFN9U9br-hBya1rohl7drXDHF4',
    appId: '1:155485410570:android:0dc0ef524c5e99f61416f3',
    messagingSenderId: '155485410570',
    projectId: 'fastcarrot-c7f71',
    databaseURL: 'https://fastcarrot-c7f71-default-rtdb.firebaseio.com',
    storageBucket: 'fastcarrot-c7f71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPorz0zBILZd8PcaF-1CyfJZmuzskH5P4',
    appId: '1:155485410570:ios:648f4b6998fddb711416f3',
    messagingSenderId: '155485410570',
    projectId: 'fastcarrot-c7f71',
    databaseURL: 'https://fastcarrot-c7f71-default-rtdb.firebaseio.com',
    storageBucket: 'fastcarrot-c7f71.appspot.com',
    iosBundleId: 'com.example.fastAppBase',
  );
}
